apiVersion: apps/v1
kind: Deployment
metadata:
  name: managerpage
  labels:
    app: managerpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: managerpage
  template:
    metadata:
      labels:
        app: managerpage
    spec:
      containers:
        - name: managerpage
          image: username/managerpage:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5